import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
export default function InputView({ requirements, onChange, apiKey, onApiKeyChange, onForgetKey, onSubmit, onDemo, error, }) {
    const [showForm, setShowForm] = useState(!!apiKey);
    return (_jsx("div", { style: {
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            minHeight: "100vh",
            background: "var(--bg-page)",
            padding: "var(--sp-6)",
        }, children: _jsxs("div", { style: { width: "100%", maxWidth: 520 }, children: [_jsx("h1", { style: {
                        fontFamily: "var(--font-display)",
                        fontSize: 28,
                        fontWeight: 700,
                        color: "var(--text-primary)",
                        margin: "0 0 8px",
                    }, children: "SiteScope" }), _jsx("p", { style: {
                        fontFamily: "var(--font-body)",
                        fontSize: 14,
                        color: "var(--text-secondary)",
                        margin: "0 0 28px",
                        lineHeight: 1.5,
                    }, children: "AI-powered data center site screening. Enter your requirements, get a ranked market dossier across power, community, incentives, and risk." }), !showForm ? (_jsxs("div", { style: { display: "flex", gap: 10 }, children: [_jsx("button", { type: "button", onClick: onDemo, style: {
                                flex: 1,
                                padding: "10px 16px",
                                background: "var(--bg-surface)",
                                border: "1px solid var(--border)",
                                borderRadius: 4,
                                fontFamily: "var(--font-body)",
                                fontSize: 14,
                                color: "var(--text-primary)",
                                cursor: "pointer",
                            }, children: "See a Demo" }), _jsx("button", { type: "button", className: "btn-primary", onClick: () => setShowForm(true), style: { flex: 1 }, children: "Run a Screen" })] })) : (_jsxs("form", { onSubmit: onSubmit, children: [error && (_jsx("p", { style: {
                                fontFamily: "var(--font-body)",
                                fontSize: 13,
                                color: "var(--signal-red-text)",
                                margin: "0 0 12px",
                            }, children: error })), _jsx("label", { style: {
                                display: "block",
                                fontFamily: "var(--font-mono)",
                                fontSize: 11,
                                color: "var(--text-tertiary)",
                                textTransform: "uppercase",
                                letterSpacing: "0.06em",
                                marginBottom: 6,
                            }, children: "Subconscious API Key" }), _jsxs("div", { style: { display: "flex", gap: 8, marginBottom: 16 }, children: [_jsx("input", { type: "password", value: apiKey, onChange: (e) => onApiKeyChange(e.target.value), placeholder: "sky_\u2026", required: true, autoComplete: "off", style: {
                                        flex: 1,
                                        background: "var(--bg-surface)",
                                        border: "1px solid var(--border)",
                                        borderRadius: 4,
                                        padding: "8px 10px",
                                        fontFamily: "var(--font-mono)",
                                        fontSize: 13,
                                        color: "var(--text-primary)",
                                        outline: "none",
                                    } }), apiKey && (_jsx("button", { type: "button", onClick: onForgetKey, style: {
                                        padding: "8px 10px",
                                        background: "none",
                                        border: "1px solid var(--border)",
                                        borderRadius: 4,
                                        fontFamily: "var(--font-body)",
                                        fontSize: 12,
                                        color: "var(--text-tertiary)",
                                        cursor: "pointer",
                                        whiteSpace: "nowrap",
                                    }, children: "Forget key" }))] }), _jsx("p", { style: {
                                fontFamily: "var(--font-body)",
                                fontSize: 11,
                                color: "var(--text-tertiary)",
                                margin: "0 0 16px",
                                lineHeight: 1.5,
                            }, children: "Your key stays in your browser and is sent only to Subconscious. Stored in localStorage." }), _jsx("label", { style: {
                                display: "block",
                                fontFamily: "var(--font-mono)",
                                fontSize: 11,
                                color: "var(--text-tertiary)",
                                textTransform: "uppercase",
                                letterSpacing: "0.06em",
                                marginBottom: 6,
                            }, children: "Requirements" }), _jsx("textarea", { value: requirements, onChange: (e) => onChange(e.target.value), rows: 6, required: true, style: {
                                width: "100%",
                                background: "var(--bg-surface)",
                                border: "1px solid var(--border)",
                                borderRadius: 4,
                                padding: 12,
                                fontFamily: "var(--font-body)",
                                fontSize: 14,
                                color: "var(--text-primary)",
                                resize: "vertical",
                                outline: "none",
                                display: "block",
                                boxSizing: "border-box",
                            } }), _jsxs("div", { style: { display: "flex", gap: 10, marginTop: 12 }, children: [_jsx("button", { type: "button", onClick: () => setShowForm(false), style: {
                                        padding: "10px 16px",
                                        background: "none",
                                        border: "1px solid var(--border)",
                                        borderRadius: 4,
                                        fontFamily: "var(--font-body)",
                                        fontSize: 14,
                                        color: "var(--text-tertiary)",
                                        cursor: "pointer",
                                    }, children: "Back" }), _jsx("button", { type: "submit", className: "btn-primary", style: { flex: 1 }, children: "Run Screening" })] })] }))] }) }));
}
